### ISSUE TITLE
🐞 Prod error - create new user

### ISSUE THREAD

**Issue by unrealsolver** [iTechLibrary/mimir#347]
- Environment: https://mimirapp.xyz/
- Client: FF

### ✔️ Expected behavior
User should be able to Sign Up (register)

### ✖️ Actual behavior
500 Error happens when user is new.

### Screenshot / Descriptions
```
0|apiserver  | Error: Cannot find module './InsertQueryBuilder'
0|apiserver  | Require stack:
0|apiserver  | - /srv/apiserver/node_modules/typeorm/query-builder/QueryBuilder.js
0|apiserver  | - /srv/apiserver/node_modules/typeorm/query-builder/SelectQueryBuilder.js
0|apiserver  | - /srv/apiserver/node_modules/typeorm/connection/Connection.js
0|apiserver  | - /srv/apiserver/node_modules/typeorm/connection/ConnectionManager.js
0|apiserver  | - /srv/apiserver/node_modules/typeorm/globals.js
0|apiserver  | - /srv/apiserver/node_modules/typeorm/index.js
0|apiserver  | - /srv/apiserver/node_modules/@nestjs/typeorm/dist/common/typeorm.utils.js
0|apiserver  | - /srv/apiserver/node_modules/@nestjs/typeorm/dist/common/typeorm.decorators.js
0|apiserver  | - /srv/apiserver/node_modules/@nestjs/typeorm/dist/common/index.js
0|apiserver  | - /srv/apiserver/node_modules/@nestjs/typeorm/dist/index.js
0|apiserver  | - /srv/apiserver/node_modules/@nestjs/typeorm/index.js
0|apiserver  | - /srv/apiserver/main.js
0|apiserver  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
0|apiserver  |     at Module.Hook._require.Module.require (/home/app/.nvm/versions/node/v16.16.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|apiserver  |     at require (node:internal/modules/cjs/helpers:102:18)
0|apiserver  |     at SelectQueryBuilder.QueryBuilder.insert (/srv/apiserver/node_modules/typeorm/query-builder/QueryBuilder.js:92:37)
0|apiserver  |     at /srv/apiserver/node_modules/typeorm/persistence/SubjectExecutor.js:292:50
0|apiserver  |     at step (/srv/apiserver/node_modules/tslib/tslib.js:144:27)
0|apiserver  |     at Object.next (/srv/apiserver/node_modules/tslib/tslib.js:125:57)
0|apiserver  |     at step (/srv/apiserver/node_modules/tslib/tslib.js:129:143)
0|apiserver  |     at Object.next (/srv/apiserver/node_modules/tslib/tslib.js:125:57)
0|apiserver  |     at /srv/apiserver/node_modules/tslib/tslib.js:118:75
```

**Comment by unrealsolver** [comment]
Fixed by redeploying. Broken GH job was disabled.
